name: push_daydayup_api_image

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ./DayDayUp.API.sln --configuration Release

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: jerray/publish-docker-action@master
      name: Publish docker image
      with:
        repository: googboyymh/daydayup-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
