name: push_daydayup_api_image

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build with dotnet
      run: dotnet build ./DayDayUp.API.sln --configuration Release

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: googboyymh/daydayup-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
