name: push_daydayup_api_image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Publish docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker build -t googboyymh/daydayup-api:latest .
        docker push goodboyymh/daydayup-api:latest
