name: push_daydayup_api_image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: elgohr/Publish-Docker-Github-Action@2.7
      name: Publish docker image
      with:
        name: googboyymh/daydayup-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ../../src/DayDayUp.API/Dockerfile
